### ISSUE TITLE
Playlist ToDo

### ISSUE THREAD

**Issue by SonQHoang** [SonQHoang/Soundify#60]

**Comment by SonQHoang** [comment]
- [ ] Figure out how to add graphics
- [ ] Figure out how to add images
- [ ] Figure out how to keep playlist information there for when the user returns (Permantely in state)
- [ ] Query Album Title information
- [ ] Get Clock Favicon
