### ISSUE TITLE
Albums ToDo

### ISSUE THREAD

**Issue by SonQHoang** [SonQHoang/Soundify#61]
- [x] Add album image
- [x] Add song funtionality for albums
- [x] Get Clock favicon
